### PR TITLE
[proxima] add serialVersionUID to relevant Serializable classes

### PR DESCRIPTION
**Pull request by je-ik**

### CODE REVIEW

**Comment by je-ik** [comment]
cc @dmvk

**Comment by dmvk** [comment]
LGTM 👍

**Comment by dmvk** [comment]
Is it possible to introduce a check for spotbugs / sonar, that ensures all serializables use this?

**Comment by je-ik** [comment]
It is not. I actually tried to put this to error prone, but
 a) I couldn't make it work, and
 b) there are many cases where you don't want that, so it cannot be as a rule
Obvious examples are `DoFn`s, `PTransform`s, etc.

**Pull request merged**
